"""Adds storeAddress table

Revision ID: cda9daddc389
Revises: f19448ca7120
Create Date: 2026-06-02 23:05:12.160531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda9daddc389'
down_revision = 'f19448ca7120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Shipping', 'Billing'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stores_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'store_addresses', ['store_address_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stores_ibfk_2'), 'addresses', ['store_address_id'], ['id'], ondelete='SET NULL')

    op.drop_table('store_addresses')
    # ### end Alembic commands ###
