"""Initial migration

Revision ID: f19448ca7120
Revises: 
Create Date: 2026-06-02 12:29:57.815320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f19448ca7120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('Shipping', 'Billing'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_id', sa.String(length=100), nullable=False),
    sa.Column('proof_of_address', sa.String(length=100), nullable=False),
    sa.Column('business_registration_certificate', sa.String(length=100), nullable=False),
    sa.Column('business_permit', sa.String(length=100), nullable=False),
    sa.Column('bir_certificate', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'addresses', ['store_address_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('address')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_roles_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_ibfk_1'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_roles_ibfk_2'), 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_address_id')

    op.drop_table('store_documents')
    op.drop_table('addresses')
    # ### end Alembic commands ###
